# Generated by Django 5.0.3 on 2024-04-02 17:55

import django.db.models.deletion
import room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default=room.models.generate_room_id, max_length=16, unique=True)),
                ('player_a', models.CharField(blank=True, max_length=50, null=True)),
                ('player_a_color', models.CharField(blank=True, max_length=5, null=True)),
                ('player_b', models.CharField(blank=True, max_length=50, null=True)),
                ('player_b_color', models.CharField(blank=True, max_length=5, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished')], default='WAITING', max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('winner', models.CharField(blank=True, default='Unknown', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=100)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
