# Generated by Django 5.0.3 on 2024-04-03 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_match_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='test',
        ),
    ]
