# Generated by Django 5.0.3 on 2024-04-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_remove_match_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='practice',
            field=models.BooleanField(default=False),
        ),
    ]
