# Generated by Django 5.0.3 on 2024-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='winner',
            field=models.CharField(blank=True, default='Unknown', max_length=10, null=True),
        ),
    ]
