# Generated by Django 5.0.3 on 2024-04-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='player_a',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='player_b',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
